// Mocks generated by Mockito 5.0.0-nullsafety.7 from annotations
// in starter_architecture_flutter_firebase/test/onboarding_view_model_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i2;
import 'package:starter_architecture_flutter_firebase/services/shared_preferences_service.dart'
    as _i3;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeSharedPreferences extends _i1.Fake implements _i2.SharedPreferences {
}

/// A class which mocks [SharedPreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferencesService extends _i1.Mock
    implements _i3.SharedPreferencesService {
  MockSharedPreferencesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SharedPreferences get sharedPreferences =>
      (super.noSuchMethod(Invocation.getter(#sharedPreferences),
          returnValue: _FakeSharedPreferences()) as _i2.SharedPreferences);
  @override
  _i4.Future<void> setOnboardingComplete() =>
      (super.noSuchMethod(Invocation.method(#setOnboardingComplete, []),
          returnValue: Future.value(null),
          returnValueForMissingStub: Future.value()) as _i4.Future<void>);
  @override
  bool isOnboardingComplete() =>
      (super.noSuchMethod(Invocation.method(#isOnboardingComplete, []),
          returnValue: false) as bool);
}
