name: Run Tests
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v2.8.0
      - run: flutter pub get
      - run: flutter pub run build_runner build  --delete-conflicting-outputs
      - name: Run Flutter tests
        run: flutter test
